<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PowerupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PowerupRepository extends EntityRepository
{
    /**
     * @param float $lat
     * @param float $lng
     * @param int $radius The radius in km
     * @return array
     */
    public function findInRadius($lat, $lng, $radius = 5) {
        return $this->getEntityManager()
            ->createQuery(
                sprintf(
                    "SELECT p.id, p.latitude, p.longitude, radius(%f, %f) distance, p.type
                        FROM AppBundle:Powerup p
                        HAVING distance < %d
                        ORDER BY distance",
                    $lat, $lng, $radius)
            )->getResult();
    }
}
